name: Password Check

on: [push]

jobs:
  check-password:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check Password
        id: check_password
        run: |
          if [ "${{ secrets.MY_SECRET_PASSWORD }}" == "correct_password" ]; then
            echo "Hi, Roman"
          else
            echo "Authentication failed. Please check your password."
            exit 1
          fi
